# Generated by Django 4.2.5 on 2023-12-02 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pokemons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tamano', models.IntegerField(default=3)),
                ('especiesPokemon', models.ManyToManyField(to='Pokemons.especiepokemon')),
                ('pokemons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pokemons.pokemon')),
            ],
        ),
    ]
