# Generated by Django 4.2.5 on 2024-01-31 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Equipos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspeciePokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipoPrincipal', models.CharField(max_length=50)),
                ('tipoSecundario', models.CharField(max_length=50)),
                ('vidaBase', models.IntegerField(default=200)),
                ('ataqueBase', models.IntegerField(default=50)),
                ('defensaBase', models.IntegerField(default=30)),
                ('ataqueEspecialBase', models.IntegerField(default=50)),
                ('defensaEspecialBase', models.IntegerField(default=30)),
                ('velocidadBase', models.IntegerField(default=100)),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield')),
                ('imagenFrente', models.BinaryField(blank=True, null=True)),
                ('imagenEspalda', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('potencia', models.IntegerField(default=100)),
                ('precision', models.IntegerField(default=100)),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipoPrincipal', models.CharField(max_length=50)),
                ('tipoSecundario', models.CharField(max_length=50)),
                ('vida', models.IntegerField(default=100)),
                ('ataque', models.IntegerField(default=100)),
                ('defensa', models.IntegerField(default=100)),
                ('ataqueEspecial', models.IntegerField(default=100)),
                ('defensaEspecial', models.IntegerField(default=100)),
                ('velocidad', models.IntegerField(default=100)),
                ('nivel', models.IntegerField(default=100)),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Equipos.equipopokemon')),
                ('especie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pokemons.especiepokemon')),
                ('movimientos', models.ManyToManyField(to='Pokemons.movimiento')),
            ],
        ),
        migrations.AddField(
            model_name='especiepokemon',
            name='movimientos',
            field=models.ManyToManyField(to='Pokemons.movimiento'),
        ),
    ]
