# Generated by Django 4.2.5 on 2024-02-27 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Equipos', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptada', models.BooleanField()),
                ('equipo_destinatario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_como_destinatario', to='Equipos.equipopokemon')),
                ('equipo_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_como_solicitante', to='Equipos.equipopokemon')),
                ('usuario_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_recibidas', to='Usuarios.perfilusuario')),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_solicitadas', to='Usuarios.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Batalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField()),
                ('equipo_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batallas_como_receptor', to='Equipos.equipopokemon')),
                ('equipo_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batallas_como_solicitante', to='Equipos.equipopokemon')),
                ('usuario_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batallas_recibidas', to='Usuarios.perfilusuario')),
                ('usuario_ganador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batallas_ganadas', to='Usuarios.perfilusuario')),
                ('usuario_perdedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batallas_perdidas', to='Usuarios.perfilusuario')),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batallas_solicitadas', to='Usuarios.perfilusuario')),
            ],
        ),
    ]
